name: Update Metrics

on:
  schedule:
    - cron: "0 18 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - name: Half-year calendar
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics/general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Takashicc
          template: classic
          config_timezone: Asia/Tokyo
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
